### ISSUE TITLE
demo code

### ISSUE THREAD

**Issue by lime-green** [xeniatay/cs349#1]
Hey there Xenia! I like your work. Would you mind if I copied your two functions: `initDemoImages` and `loadImagesFromLS` so my image uploading works properly? :)

Let me know,
Josh

**Comment by xeniatay** [comment]
Go for it! :) Anyone is welcome to use them :ok_woman:

**Comment by xeniatay** [comment]
@lime-green Note: you also have to modify `loadImageCollectionModel` in `models.js`:

```
function loadImageCollectionModel(modelsJSON) {
        var imageCollectionModel = new ImageCollectionModel(),
            modelsJSON = modelsJSON || localStorage.getItem('imageCollectionModel');
```
